#! /usr/bin/env python
"""Executes a data analysis pipeline given a pipeline file.

This script, when executed on the command line, accepts a single parameter,
the path to a pipeline file.
"""


import argparse


def run(pipefile):
    from dslpipe.pipeline.pipeline import Manager

    P = Manager(pipefile)
    P.run()


parser = argparse.ArgumentParser(description='The pipeline manager.')
parser.add_argument('pipefile', type=str, nargs='?', help='Input parameter setting file to run the pipeline.')
parser.set_defaults(func=run)

args = parser.parse_args()
args.func(args.pipefile)
